apiVersion: v2
name: ccplant
description: A Helm chart for deploying agentapi-proxy backend and frontend
type: application
version: 0.1.0-dev.20260119091911.b996c99
appVersion: "1.0.0"

dependencies:
  - name: agentapi-proxy
    version: "0.3.0-dev.20260119091505.8061312"
    repository: "oci://ghcr.io/takutakahashi/charts"
    alias: backend
  - name: agentapi-ui
    version: "0.1.0-dev.7d3873c"
    repository: "oci://ghcr.io/takutakahashi/charts"
    alias: frontend