apiVersion: v2
name: ccplant
description: A Helm chart for deploying agentapi-proxy backend and frontend
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: agentapi-proxy
    version: "0.3.0"
    repository: "file://../../../agentapi-proxy/helm/agentapi-proxy"
  - name: agentapi-ui
    version: "v0.1.0"
    repository: "file://../../../agentapi-ui/helm/agentapi-ui"